### ISSUE TITLE
Hitting search endpoint fails

### ISSUE THREAD

**Issue by lasseborly** [os2display/docs#12]
When I go to ex. `https://admin.os2display.vm/#/channel-overview`.
It won't load any any channels, slides or screens and the request returns me errors:

![search](https://user-images.githubusercontent.com/2671660/43957052-b0e82ece-9ca6-11e8-9b5c-6ee29a179f16.png)

I have tried restarting the search service but to no avail:

![search](https://user-images.githubusercontent.com/2671660/43957100-e4097506-9ca6-11e8-97bb-c46efafad9e2.png)

I can't create any resources to populate the search endpoint either.

**Comment by tuj** [comment]
I'm assuming you are using Chrome?
Visit https://search.os2display.vm and accept the self-signed certificate.

**Comment by lasseborly** [comment]
Cool! Is that in the docs somewhere I have missed or can I submit a PR? 😊

**Comment by tuj** [comment]
https://github.com/os2display/admin#information :)

**Comment by lasseborly** [comment]
My bad then! Sorry for the inconvinience.
